version: '3'
services:
  frontend:
    build: .
    environment:
      - VUE_APP_BASE_URL
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: yarn serve
    depends_on:
      - api
