version: '3'
services:
  api:
    build:
      context: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    environment:
      - VUE_APP_BASE_URL=http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    command: yarn serve
    depends_on:
      - api

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
